### List vs numpy

In [1]:
import numpy as np

In [2]:
py_list = [1,2,3]
print(f"Python list multiplication {py_list*2}")

Python list multiplication [1, 2, 3, 1, 2, 3]


In [3]:
np_array = np.array(py_list)
print(f"Python list multiplication {np_array*2}")


Python list multiplication [2 4 6]


In [4]:
import time

start = time.time()
py_list = [i*2 for i in range(1000000)]
print(f"List operation time: {time.time()-start}")

List operation time: 0.03160810470581055


In [29]:
%%time
py_list = [i*2 for i in range(1000000)]
print(f"List operation time: ")

List operation time: 
CPU times: user 41.8 ms, sys: 14.6 ms, total: 56.4 ms
Wall time: 92.2 ms


In [30]:
%%time
np_array = np.arange(1000000)*2
print(f"Numpy operation time: ")


Numpy operation time: 
CPU times: user 1.38 ms, sys: 2.13 ms, total: 3.51 ms
Wall time: 3.27 ms


### Creating array from scratch

In [8]:
zeros = np.zeros((3,4)) 
print("Zeros array: \n",zeros)


ones = np.ones((2,3)) 
print("Ones array: \n",ones)

full = np.full((2,2),7) 
print("full array: \n",full)

Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]


In [9]:
random = np.random.random([2,3])
print("random array: \n", random)

random array: 
 [[0.90109487 0.05888146 0.66856503]
 [0.026106   0.43945331 0.54631806]]


In [11]:
sequence = np.arange(0,11,2)
print("Sequence array: \n", sequence)


Sequence array: 
 [ 0  2  4  6  8 10]


### Vector, Matrix and Tensor

In [12]:
vector = np.array([1,2,3])
print("Vector: ",vector)

Vector:  [1 2 3]


In [14]:
matrix = np.array([[1,2,3],[4,5,6]])
print("matrix: ",matrix)

matrix:  [[1 2 3]
 [4 5 6]]


In [16]:
tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("tensor: ",tensor)

tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [22]:
arr = np.array([[1,2,3],
                [4,5,6]])

print("Shape ", arr.shape)
print("Dimension ", arr.ndim)
print("Size ", arr.size)
print("DType ", arr.dtype)

Shape  (2, 3)
Dimension  2
Size  6
DType  int64


### Array Reshaping

In [31]:
arr = np.arange(12)

print(f"Original Array: {arr}")

reshaped = arr.reshape((3,4))
print(f"Reshaped Array: {reshaped}")


flattened = reshaped.flatten()
print(f"Flattened Array: {flattened}")


raveled = reshaped.ravel()
print(f"Raveled  Array: {raveled}")



Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled  Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
