In [1]:
import numpy as np

In [12]:
integers = np.array([[1,2,3],[4,5,6]])
print(integers)
print(integers.dtype)
print(integers.ndim)
print(integers.shape)
print(integers.size) # no of rows * columns
print(integers.itemsize) # how many bytes are used to store each elements


[[1 2 3]
 [4 5 6]]
int64
2
(2, 3)
6
8


In [10]:
floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])

print(floats)
print(floats.dtype)
print(floats.ndim)
print(floats.shape)

[0.  0.1 0.2 0.3 0.4]
float64
1
(5,)


### iterate

In [13]:
for row in integers:
    for column in row:
        print(column,end=' ')
    print()

1 2 3 
4 5 6 


In [14]:
for i in integers.flat:
    print(i,end=' ')

1 2 3 4 5 6 

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.ones((2,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [26]:
np.full((3,5),np.random.random())

array([[0.62690331, 0.62690331, 0.62690331, 0.62690331, 0.62690331],
       [0.62690331, 0.62690331, 0.62690331, 0.62690331, 0.62690331],
       [0.62690331, 0.62690331, 0.62690331, 0.62690331, 0.62690331]])

In [27]:
np.full((3,5),12)


array([[12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12]])

In [20]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [21]:
np.arange(5,10)


array([5, 6, 7, 8, 9])

In [22]:
np.arange(10, 1, -2)

array([10,  8,  6,  4,  2])

In [28]:
np.linspace(0.0, 1.0, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [29]:
np.arange(1, 21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [30]:
np.arange(1, 100001).reshape(4,25000)

array([[     1,      2,      3, ...,  24998,  24999,  25000],
       [ 25001,  25002,  25003, ...,  49998,  49999,  50000],
       [ 50001,  50002,  50003, ...,  74998,  74999,  75000],
       [ 75001,  75002,  75003, ...,  99998,  99999, 100000]])

In [31]:
np.arange(1, 100001).reshape(100,1000)

array([[     1,      2,      3, ...,    998,    999,   1000],
       [  1001,   1002,   1003, ...,   1998,   1999,   2000],
       [  2001,   2002,   2003, ...,   2998,   2999,   3000],
       ...,
       [ 97001,  97002,  97003, ...,  97998,  97999,  98000],
       [ 98001,  98002,  98003, ...,  98998,  98999,  99000],
       [ 99001,  99002,  99003, ...,  99998,  99999, 100000]])

In [32]:
numbers= np.arange(2, 41)
numbers[numbers % 2 == 0].reshape(4,5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [35]:
np.arange(2,41,2).reshape(4,5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

### List vs array performance

In [40]:
import random
%timeit rolls_list = [random.randrange(1,7) for i in range(6_000_000)]

1.25 s ± 34.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [39]:
%timeit rolls_array = np.random.randint(1, 7, 6_000_000)

44.5 ms ± 285 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [41]:
%timeit rolls_array = np.random.randint(1, 7, 60_000_000)

457 ms ± 41.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [42]:
%timeit rolls_array = np.random.randint(1, 7, 600_000_000)

4.51 s ± 70.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [43]:
%timeit -n3 -r2 rolls_array = np.random.randint(1, 7, 6_000_000)

54.8 ms ± 11.1 ms per loop (mean ± std. dev. of 2 runs, 3 loops each)


In [44]:
%timeit list_sum = sum([x for x in range(10_000_000)])

252 ms ± 2.68 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [45]:
%timeit np_array_sum = np.arange(10_000_000).sum()

9.99 ms ± 49.5 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Array Operators

In [51]:
numbers = np.arange(1,6)
display(numbers)

array([1, 2, 3, 4, 5])

In [52]:
numbers * 2 # prodcasting

array([ 2,  4,  6,  8, 10])

In [53]:
numbers ** 3

array([  1,   8,  27,  64, 125])

In [54]:
numbers += 10
display(numbers)

array([11, 12, 13, 14, 15])

In [55]:
numbers2 = np.linspace(1.1, 5.5, 5)
display(numbers2)


array([1.1, 2.2, 3.3, 4.4, 5.5])

In [57]:
numbers * numbers2

array([12.1, 26.4, 42.9, 61.6, 82.5])

In [58]:
numbers >= 13


array([False, False,  True,  True,  True])

In [59]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [60]:
numbers2 < numbers

array([ True,  True,  True,  True,  True])

In [61]:
numbers == numbers2

array([False, False, False, False, False])

### Calculation

In [64]:
grades = np.array([[87,96,70],[100,87,90],[94, 77, 90],[100,81,82]])
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [65]:
grades.sum()

1054

In [66]:
grades.min()

70

In [67]:
grades.max()

100

In [68]:
grades.mean()

87.83333333333333

In [69]:
grades.std()

8.792357792739987

In [70]:
grades.var()

77.30555555555556

In [ ]:
grades.mean(axis=0) # col * col

array([95.25, 85.25, 83.  ])

In [ ]:
grades.mean(axis=1) # row * row

array([84.33333333, 92.33333333, 87.        , 87.66666667])

In [73]:
grades.mean?

Docstring:
a.mean(axis=None, dtype=None, out=None, keepdims=False, *, where=True)

Returns the average of the array elements along given axis.

Refer to `numpy.mean` for full documentation.

See Also
--------
numpy.mean : equivalent function
Type:      builtin_function_or_method

In [81]:
grades = np.random.randint(60,101,12).reshape(3,4)
grades


array([[ 85,  84,  98,  75],
       [ 89, 100,  89,  70],
       [100,  76,  64,  94]])

In [83]:
grades.mean()

85.33333333333333

In [85]:
grades.mean(axis=0)

array([91.33333333, 86.66666667, 83.66666667, 79.66666667])

In [84]:
grades.mean(axis=1)


array([85.5, 87. , 83.5])

In [93]:
numbers = np.array([1,4,9,16,25,36])
numbers

array([ 1,  4,  9, 16, 25, 36])

In [94]:
np.sqrt(numbers)

array([1., 2., 3., 4., 5., 6.])

In [95]:
numbers2 = np.arange(1, 7) * 10

numbers2

array([10, 20, 30, 40, 50, 60])

In [96]:
np.add(numbers,numbers2)

array([11, 24, 39, 56, 75, 96])

In [ ]:
np.multiply(numbers2,5)

array([ 50, 100, 150, 200, 250, 300])

In [98]:
numbers3 = numbers2.reshape(2,3)
numbers3

array([[10, 20, 30],
       [40, 50, 60]])

In [99]:
numbers4 = np.array([2,4,6])

In [100]:
np.multiply(numbers3,numbers4)

array([[ 20,  80, 180],
       [ 80, 200, 360]])

### Indexing and Slicing